### ISSUE TITLE
Adapt to PSR-7

### ISSUE THREAD

**Issue by sorenmalling** [neos/flow-welcome#8]
Starting the development server after installing latest dev-master gives you the following error

<img width="870" alt="Screenshot 2019-08-21 at 18 42 15" src="https://user-images.githubusercontent.com/531918/63451294-2d662580-c444-11e9-815b-3c424c20cd69.png">

This is due to this code in the standardcontroller

<img width="528" alt="Screenshot 2019-08-21 at 18 45 32" src="https://user-images.githubusercontent.com/531918/63451295-2dfebc00-c444-11e9-8d34-26dc1dd3b3b4.png">

We will have to adapt it  to psr-7 implementation in latest Flow version

**Comment by albe** [comment]
Fixed with https://github.com/neos/flow-welcome/commit/fa290a814ce406eca3d57ab0a22730cf1b124d69 ;)
